version: "3.9"

services:
  db:
    image: gvenzl/oracle-xe
    restart: always
    container_name: db
    environment:
      ORACLE_PASSWORD: rootSenha
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/var/lib/oracle/data
    networks:
      - mynetwork

  app:
    image: davisants/smart_traffic
    restart: always
    build: ./smart_traffic
    working_dir: /app
    container_name: smart_traffic
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//db:1521/xe
      SPRING_DATASOURCE_USERNAME: SYSTEM
      SPRING_DATASOURCE_PASSWORD: rootSenha
      SPRING_APPLICATION_NAME: smart_traffic_management_system
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  oracle-data: